# Anytime we're making use of docker we need to have superuser level permissions
sudo: required

services:
  - docker  # We need Docker-CLI pre-installed

# before_install will have series of commands that get executed before our tests are ran or before deploying the application
before_install:
  - docker build -t rishab189/docker-react -f Dockerfile.dev . 

# The script section contains all the different commands that need to be executed to actually run our test suite
# If the output of each of these commands return status code other than 0, Travis is going to assume that our build failed
# Anytime that we run our test suite on Travis CI, Travis is going to assume that our test suite runs and then exits automatically 
script:
  - docker run -e CI=true rishab189/docker-react npm run test